### ISSUE TITLE
return time for flank not added to burn times

### ISSUE THREAD

**Issue by crawld** [teamholtz/DripTorch#60]
For flank patterns, the crew ignites in one direction and travels back in the opposite direction without new ignitions. It doesn't appear the return trip is reflected in the output times. this is v0.4.0

**Comment by lucaswells** [comment]
Thanks, @crawld. I changed the flank fire technique to automatically compute the depth between ignitors so that there is only one heat and the ignitors don't travel downwind with fire in the unit. To my knowledge, this is typical on Rx burns. I'm closing this issue for now, but we can reopen it if we need to include the return traverse time for multi-heat patterns.

**Comment by lucaswells** [comment]
Reopening this issue to add an optional depth argument to the flank firing technique.
